name: javascript API client generation using api.yaml

on:
  push:
    paths:
      - daemon/api/api.yaml

jobs:
  generate-javascript-client:
    runs-on: ubuntu-latest

    name: generate javascript client
    steps:
      - uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: javascript
          openapi-url: https://raw.githubusercontent.com/opensvc/om3/main/daemon/api/api.yaml

      #- uses: actions/checkout@v4
      #  with:
       #   repository: remimendes/testOpenApiGen
          #  path: testOpenApiGen
            #  sparse-checkout: |
          #    .git
        #  sparse-checkout-cone-mode: false

      - run: |
         mkdir -p testOpenApiGen/.git
         cd testOpenApiGen/.git
         git clone --bare https://${{ secrets.ACCESS_TOKEN }}@github.com/remimendes/testOpenApiGen.git
         cd ../..
         cp -r javascript-client/* testOpenApiGen/
         cd testOpenApiGen
         git config --global user.email "you@example.com"
         git config --global user.name "Your Name"
         git checkout -b feature-branch
         git commit -a -m "msg"
         git push origin feature-branch
         echo "${{ secrets.ACCESS_TOKEN }}" > token.txt
         gh auth login --with-token < token.txt
         gh pr create \
           --body "" \
           --title "title" \
           --head "feature-branch" \
           --base "main"

