name: javascript API client generation using api.yaml

on:
  push:
    paths:
      - daemon/api/api.yaml

jobs:
  generate-javascript-client:
    runs-on: ubuntu-latest

    name: generate javascript client
    steps:
      - uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: javascript
          openapi-url: https://raw.githubusercontent.com/remimendes/om3/main/daemon/api/api.yaml

      #- uses: actions/checkout@v4
      #  with:
       #   repository: remimendes/testOpenApiGen
          #  path: testOpenApiGen
            #  sparse-checkout: |
          #    .git
        #  sparse-checkout-cone-mode: false

      - run: |
         git clone --no-checkout https://${{ secrets.ACCESS_TOKEN }}@github.com/remimendes/testOpenApiGen.git
         cp -a javascript-client/. testOpenApiGen/
         cd testOpenApiGen
         ls -a
         git config --global user.email "you@example.com"
         git config --global user.name "Your Name"
         git checkout -b feature-branch
         git add .
          cat package.json
          cat package.json | jq 
         echo "=$(git status -s)="
         #if [ -z "$(git status -s)" ]; then
         # echo "there are no changes in the code generated by codegen"
         # exit 0
         #fi
         date >> README.md
          git add README.md
          git commit -m m README.md
             git status
         git commit -m "msg"
         git push origin feature-branch --force
         echo "${{ secrets.ACCESS_TOKEN }}" > token.txt
         gh auth login --with-token < token.txt
         gh pr create \
           --body "" \
           --title "title" \
           --head "feature-branch" \
           --base "main"

