name: javascript API client generation using api.yaml

on:
  push:
    paths:
      - daemon/api/api.yaml #TODO trigger when a pr is merged

jobs:
  generate-javascript-client:
    runs-on: ubuntu-latest

    name: generate javascript client
    steps:
      - uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: javascript
          openapi-url: https://raw.githubusercontent.com/remimendes/om3/main/daemon/api/api.yaml #TODO use the repo of opensvc

      #- uses: actions/checkout@v4
      #  with:
       #   repository: remimendes/testOpenApiGen
          #  path: testOpenApiGen
            #  sparse-checkout: |
          #    .git
        #  sparse-checkout-cone-mode: false
      #TODO git clone & wget remimendes --> opensvc
      - run: |
         git clone --no-checkout https://${{ secrets.ACCESS_TOKEN }}@github.com/remimendes/testOpenApiGen.git
         mkdir -p testOpenApiGen/.github/workflows
         cd testOpenApiGen/.github/workflows
         wget https://raw.githubusercontent.com/remimendes/testOpenApiGen/main/.github/workflows/release.yml
         cd -
         cp -a javascript-client/. testOpenApiGen/
         cd testOpenApiGen
         PVERSION="$(git describe --tags --abbrev=0)"
         ls -a
         git config --global user.email "you@example.com"
         git config --global user.name "Your Name"
         date >> README.md
         git add .
         VERSION="$(cat package.json | jq '.version')"
         if [ "$VERSION" = "$PVERSION" ] ; then
             echo no change $VERSION
             exit 0
         fi
         echo "change $PVERSION -> $VERSION"
         if [ -z "$(git status -s)" ]; then
             echo "there are no changes in the code generated by codegen"
             exit 0
         fi
         git status
         git commit -m "create new version $VERSION"
         git tag $VERSION
         git push origin
         git push --tags